"""Characterization (golden) test for the restore-tier status-string fractal.

This pins the EXACT current output of every pure ``(status: str) -> str`` classifier
in the ``operator_resolution_trend`` restore-tier machinery, across the full status
vocabulary, to a frozen golden file. It is the safety net for the
``recovery_state(target, *, depth)`` collapse: any change to the depth-tier
translation behavior shows up here as a byte-level diff before it can reach a
consumer.

Regenerate the golden only with an intentional, reviewed behavior change:
    uv run python tests/golden/enumerate_recovery_state_contract.py

The golden is generated by executing the modules (never by hand), so it cannot
silently drift from real behavior.
"""

from __future__ import annotations

import importlib
import json
from pathlib import Path

import pytest

GOLDEN_PATH = Path(__file__).parent / "golden" / "recovery_state_contract.golden.json"
GOLDEN: dict[str, dict[str, str]] = json.loads(GOLDEN_PATH.read_text())


def _resolve(qualname: str) -> object:
    module_name, _, attr = qualname.rpartition(".")
    module = importlib.import_module(module_name)
    return getattr(module, attr)


def test_golden_is_non_empty_and_exercises_branches() -> None:
    # Guard against a degenerate golden (e.g. one that records only "none").
    assert GOLDEN, "golden contract is empty"
    nontrivial = sum(
        1 for rows in GOLDEN.values() for value in rows.values() if value not in ("none", "")
    )
    assert nontrivial >= 1000, f"golden exercises too few real branches ({nontrivial})"


@pytest.mark.parametrize("qualname", sorted(GOLDEN))
def test_classifier_reproduces_golden(qualname: str) -> None:
    fn = _resolve(qualname)
    expected = GOLDEN[qualname]
    actual: dict[str, str] = {}
    for status, _ in expected.items():
        try:
            actual[status] = fn(status)
        except Exception as exc:  # the raise itself is part of the recorded contract
            actual[status] = f"<<RAISED {type(exc).__name__}: {exc}>>"
    assert actual == expected
