"""Top-level payload assembly for the operator resolution-trend god-function.

Extracted verbatim from ``operator_resolution_trend._build_resolution_trend``:
the 1,676-line ``payload.update({...})`` that assembles the 320+ per-target,
per-class, and per-recovery-tier keys of the resolution-trend payload from the
apply-chain and summary-context stages. The block is kept byte-identical (proven
by ``tests/test_resolution_trend_golden_contract.py``); only its container moved.

The three class-transition / hysteresis summary renderers it calls are defined in
``operator_resolution_trend`` and injected as callables here, to avoid a circular
import -- the same dependency-injection pattern the sibling extracted stages
(run-context, apply-chain, summary-context, topline-payload) already use.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any


def _emit_resolution_payload_entries(
    payload: dict[str, Any],
    *,
    primary_target: dict,
    sources: dict[str, dict],
    entries: tuple[tuple[str, str, bool], ...],
) -> None:
    """Emit per-target / per-class recovery-tier payload keys from a spec table.

    Each entry is ``(out_key, source_name, is_ternary)``; the value is read from
    ``sources[source_name][out_key]``. Ternary entries reproduce the original
    primary_target override exactly::

        primary_target.get(<out_key without "primary_target_">, value)
        if primary_target else value

    This regenerates the inline ternaries / passthrough subscripts that made up
    the bulk of the resolution-trend payload, byte-for-byte (proven by
    ``tests/test_resolution_trend_golden_contract.py``).
    """
    for out_key, source_name, is_ternary in entries:
        value = sources[source_name][out_key]
        if is_ternary:
            payload[out_key] = (
                primary_target.get(out_key.removeprefix("primary_target_"), value)
                if primary_target
                else value
            )
        else:
            payload[out_key] = value


_RESOLUTION_PAYLOAD_ENTRIES: tuple[tuple[str, str, bool], ...] = (
    ('primary_target_class_trust_momentum_score', 'class_trust_momentum', False),
    ('primary_target_class_trust_momentum_status', 'class_trust_momentum', False),
    ('primary_target_class_reweight_stability_status', 'class_trust_momentum', False),
    ('primary_target_class_reweight_transition_status', 'class_trust_momentum', False),
    ('primary_target_class_reweight_transition_reason', 'class_trust_momentum', False),
    ('class_momentum_summary', 'class_trust_momentum', False),
    ('class_reweight_stability_summary', 'class_trust_momentum', False),
    ('class_transition_window_runs', 'class_trust_momentum', False),
    ('primary_target_class_transition_health_status', 'class_transition_resolution', True),
    ('primary_target_class_transition_health_reason', 'class_transition_resolution', True),
    ('primary_target_class_transition_resolution_status', 'class_transition_resolution', True),
    ('primary_target_class_transition_resolution_reason', 'class_transition_resolution', True),
    ('class_transition_age_window_runs', 'class_transition_resolution', False),
    ('stalled_transition_hotspots', 'class_transition_resolution', False),
    ('resolving_transition_hotspots', 'class_transition_resolution', False),
    ('primary_target_transition_closure_confidence_score', 'pending_debt_freshness', True),
    ('primary_target_transition_closure_confidence_label', 'pending_debt_freshness', True),
    ('primary_target_transition_closure_likely_outcome', 'closure_forecast_momentum', True),
    ('primary_target_transition_closure_confidence_reasons', 'pending_debt_freshness', True),
    ('transition_closure_confidence_summary', 'closure_forecast_momentum', False),
    ('transition_closure_window_runs', 'pending_debt_freshness', False),
    ('primary_target_class_pending_debt_status', 'pending_debt_freshness', True),
    ('primary_target_class_pending_debt_reason', 'pending_debt_freshness', True),
    ('class_pending_debt_summary', 'closure_forecast_momentum', False),
    ('class_pending_resolution_summary', 'closure_forecast_momentum', False),
    ('class_pending_debt_window_runs', 'pending_debt_freshness', False),
    ('pending_debt_hotspots', 'pending_debt_freshness', False),
    ('healthy_pending_resolution_hotspots', 'pending_debt_freshness', False),
    ('primary_target_pending_debt_freshness_status', 'pending_debt_freshness', True),
    ('primary_target_pending_debt_freshness_reason', 'pending_debt_freshness', True),
    ('pending_debt_freshness_summary', 'closure_forecast_momentum', False),
    ('pending_debt_decay_summary', 'closure_forecast_momentum', False),
    ('stale_pending_debt_hotspots', 'pending_debt_freshness', False),
    ('fresh_pending_resolution_hotspots', 'pending_debt_freshness', False),
    ('pending_debt_decay_window_runs', 'pending_debt_freshness', False),
    ('primary_target_weighted_pending_resolution_support_score', 'pending_debt_freshness', True),
    ('primary_target_weighted_pending_debt_caution_score', 'pending_debt_freshness', True),
    ('primary_target_closure_forecast_reweight_score', 'pending_debt_freshness', True),
    ('primary_target_closure_forecast_reweight_direction', 'pending_debt_freshness', True),
    ('primary_target_closure_forecast_reweight_reasons', 'pending_debt_freshness', True),
    ('closure_forecast_reweighting_summary', 'closure_forecast_momentum', False),
    ('closure_forecast_reweighting_window_runs', 'pending_debt_freshness', False),
    ('supporting_pending_resolution_hotspots', 'pending_debt_freshness', False),
    ('caution_pending_debt_hotspots', 'pending_debt_freshness', False),
    ('primary_target_closure_forecast_momentum_score', 'closure_forecast_momentum', False),
    ('primary_target_closure_forecast_momentum_status', 'closure_forecast_momentum', False),
    ('primary_target_closure_forecast_stability_status', 'closure_forecast_momentum', False),
    ('primary_target_closure_forecast_hysteresis_status', 'closure_forecast_momentum', True),
    ('primary_target_closure_forecast_hysteresis_reason', 'closure_forecast_momentum', True),
    ('closure_forecast_momentum_summary', 'closure_forecast_momentum', False),
    ('closure_forecast_stability_summary', 'closure_forecast_momentum', False),
    ('closure_forecast_transition_window_runs', 'closure_forecast_momentum', False),
    ('sustained_confirmation_hotspots', 'closure_forecast_momentum', False),
    ('sustained_clearance_hotspots', 'closure_forecast_momentum', False),
    ('oscillating_closure_forecast_hotspots', 'closure_forecast_momentum', False),
    ('primary_target_closure_forecast_freshness_status', 'closure_forecast_decay', False),
    ('primary_target_closure_forecast_freshness_reason', 'closure_forecast_decay', False),
    ('primary_target_closure_forecast_decay_status', 'closure_forecast_decay', False),
    ('primary_target_closure_forecast_decay_reason', 'closure_forecast_decay', False),
    ('closure_forecast_freshness_summary', 'closure_forecast_decay', False),
    ('closure_forecast_decay_summary', 'closure_forecast_decay', False),
    ('stale_closure_forecast_hotspots', 'closure_forecast_decay', False),
    ('fresh_closure_forecast_signal_hotspots', 'closure_forecast_decay', False),
    ('closure_forecast_decay_window_runs', 'closure_forecast_decay', False),
    ('primary_target_closure_forecast_refresh_recovery_score', 'closure_forecast_recovery', False),
    ('primary_target_closure_forecast_refresh_recovery_status', 'closure_forecast_recovery', False),
    ('primary_target_closure_forecast_reacquisition_status', 'closure_forecast_recovery', True),
    ('primary_target_closure_forecast_reacquisition_reason', 'closure_forecast_recovery', True),
    ('closure_forecast_refresh_recovery_summary', 'closure_forecast_recovery', False),
    ('closure_forecast_reacquisition_summary', 'closure_forecast_recovery', False),
    ('closure_forecast_refresh_window_runs', 'closure_forecast_recovery', False),
    ('recovering_confirmation_hotspots', 'closure_forecast_recovery', False),
    ('recovering_clearance_hotspots', 'closure_forecast_recovery', False),
    ('primary_target_closure_forecast_reacquisition_age_runs', 'reacquisition_persistence', True),
    ('primary_target_closure_forecast_reacquisition_persistence_score', 'reacquisition_persistence', True),
    ('primary_target_closure_forecast_reacquisition_persistence_status', 'reacquisition_persistence', True),
    ('primary_target_closure_forecast_reacquisition_persistence_reason', 'reacquisition_persistence', True),
    ('closure_forecast_reacquisition_persistence_summary', 'reacquisition_persistence', False),
    ('closure_forecast_reacquisition_window_runs', 'reacquisition_persistence', False),
    ('just_reacquired_hotspots', 'reacquisition_persistence', False),
    ('holding_reacquisition_hotspots', 'reacquisition_persistence', False),
    ('primary_target_closure_forecast_recovery_churn_score', 'reacquisition_persistence', True),
    ('primary_target_closure_forecast_recovery_churn_status', 'reacquisition_persistence', True),
    ('primary_target_closure_forecast_recovery_churn_reason', 'reacquisition_persistence', True),
    ('closure_forecast_recovery_churn_summary', 'reacquisition_persistence', False),
    ('recovery_churn_hotspots', 'reacquisition_persistence', False),
    ('primary_target_closure_forecast_reacquisition_freshness_status', 'reacquisition_freshness_decay', False),
    ('primary_target_closure_forecast_reacquisition_freshness_reason', 'reacquisition_freshness_decay', False),
    ('closure_forecast_reacquisition_freshness_summary', 'reacquisition_freshness_decay', False),
    ('primary_target_closure_forecast_persistence_reset_status', 'reacquisition_freshness_decay', False),
    ('primary_target_closure_forecast_persistence_reset_reason', 'reacquisition_freshness_decay', False),
    ('closure_forecast_persistence_reset_summary', 'reacquisition_freshness_decay', False),
    ('stale_reacquisition_hotspots', 'reacquisition_freshness_decay', False),
    ('fresh_reacquisition_signal_hotspots', 'reacquisition_freshness_decay', False),
    ('closure_forecast_reacquisition_decay_window_runs', 'reacquisition_freshness_decay', False),
    ('primary_target_closure_forecast_reset_refresh_recovery_score', 'reset_reentry_recovery', True),
    ('primary_target_closure_forecast_reset_refresh_recovery_status', 'reset_reentry_recovery', True),
    ('primary_target_closure_forecast_reset_reentry_status', 'reset_reentry_recovery', True),
    ('primary_target_closure_forecast_reset_reentry_reason', 'reset_reentry_recovery', True),
    ('closure_forecast_reset_refresh_recovery_summary', 'reset_reentry_recovery', False),
    ('closure_forecast_reset_reentry_summary', 'reset_reentry_recovery', False),
    ('closure_forecast_reset_refresh_window_runs', 'reset_reentry_recovery', False),
    ('recovering_from_confirmation_reset_hotspots', 'reset_reentry_recovery', False),
    ('recovering_from_clearance_reset_hotspots', 'reset_reentry_recovery', False),
    ('primary_target_closure_forecast_reset_reentry_age_runs', 'reset_reentry_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_persistence_score', 'reset_reentry_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_persistence_status', 'reset_reentry_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_persistence_reason', 'reset_reentry_persistence', True),
    ('closure_forecast_reset_reentry_persistence_summary', 'reset_reentry_persistence', False),
    ('closure_forecast_reset_reentry_window_runs', 'reset_reentry_persistence', False),
    ('just_reentered_hotspots', 'reset_reentry_persistence', False),
    ('holding_reset_reentry_hotspots', 'reset_reentry_persistence', False),
    ('primary_target_closure_forecast_reset_reentry_churn_score', 'reset_reentry_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_churn_status', 'reset_reentry_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_churn_reason', 'reset_reentry_persistence', True),
    ('closure_forecast_reset_reentry_churn_summary', 'reset_reentry_persistence', False),
    ('reset_reentry_churn_hotspots', 'reset_reentry_persistence', False),
    ('primary_target_closure_forecast_reset_reentry_freshness_status', 'reset_reentry_freshness_decay', True),
    ('primary_target_closure_forecast_reset_reentry_freshness_reason', 'reset_reentry_freshness_decay', True),
    ('closure_forecast_reset_reentry_freshness_summary', 'reset_reentry_freshness_decay', False),
    ('primary_target_closure_forecast_reset_reentry_reset_status', 'reset_reentry_freshness_decay', True),
    ('primary_target_closure_forecast_reset_reentry_reset_reason', 'reset_reentry_freshness_decay', True),
    ('closure_forecast_reset_reentry_reset_summary', 'reset_reentry_freshness_decay', False),
    ('stale_reset_reentry_hotspots', 'reset_reentry_freshness_decay', False),
    ('fresh_reset_reentry_signal_hotspots', 'reset_reentry_freshness_decay', False),
    ('closure_forecast_reset_reentry_decay_window_runs', 'reset_reentry_freshness_decay', False),
    ('primary_target_closure_forecast_reset_reentry_refresh_recovery_score', 'reset_reentry_rebuild', True),
    ('primary_target_closure_forecast_reset_reentry_refresh_recovery_status', 'reset_reentry_rebuild', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_status', 'reset_reentry_rebuild', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reason', 'reset_reentry_rebuild', True),
    ('closure_forecast_reset_reentry_refresh_recovery_summary', 'reset_reentry_rebuild', False),
    ('closure_forecast_reset_reentry_rebuild_summary', 'reset_reentry_rebuild', False),
    ('closure_forecast_reset_reentry_refresh_window_runs', 'reset_reentry_rebuild', False),
    ('recovering_from_confirmation_reentry_reset_hotspots', 'reset_reentry_rebuild', False),
    ('recovering_from_clearance_reentry_reset_hotspots', 'reset_reentry_rebuild', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_age_runs', 'reset_reentry_rebuild_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_persistence_score', 'reset_reentry_rebuild_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_persistence_status', 'reset_reentry_rebuild_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_persistence_reason', 'reset_reentry_rebuild_persistence', True),
    ('closure_forecast_reset_reentry_rebuild_persistence_summary', 'reset_reentry_rebuild_persistence', False),
    ('closure_forecast_reset_reentry_rebuild_window_runs', 'reset_reentry_rebuild_persistence', False),
    ('just_rebuilt_hotspots', 'reset_reentry_rebuild_persistence', False),
    ('holding_reset_reentry_rebuild_hotspots', 'reset_reentry_rebuild_persistence', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_churn_score', 'reset_reentry_rebuild_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_churn_status', 'reset_reentry_rebuild_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_churn_reason', 'reset_reentry_rebuild_persistence', True),
    ('closure_forecast_reset_reentry_rebuild_churn_summary', 'reset_reentry_rebuild_persistence', False),
    ('reset_reentry_rebuild_churn_hotspots', 'reset_reentry_rebuild_persistence', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_freshness_status', 'reset_reentry_rebuild_freshness_decay', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_freshness_reason', 'reset_reentry_rebuild_freshness_decay', True),
    ('closure_forecast_reset_reentry_rebuild_freshness_summary', 'reset_reentry_rebuild_freshness_decay', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reset_status', 'reset_reentry_rebuild_freshness_decay', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reset_reason', 'reset_reentry_rebuild_freshness_decay', True),
    ('closure_forecast_reset_reentry_rebuild_reset_summary', 'reset_reentry_rebuild_freshness_decay', False),
    ('stale_reset_reentry_rebuild_hotspots', 'reset_reentry_rebuild_freshness_decay', False),
    ('fresh_reset_reentry_rebuild_signal_hotspots', 'reset_reentry_rebuild_freshness_decay', False),
    ('closure_forecast_reset_reentry_rebuild_decay_window_runs', 'reset_reentry_rebuild_freshness_decay', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_refresh_recovery_score', 'reset_reentry_rebuild_recovery', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_refresh_recovery_status', 'reset_reentry_rebuild_recovery', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_status', 'reset_reentry_rebuild_recovery', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_reason', 'reset_reentry_rebuild_recovery', True),
    ('closure_forecast_reset_reentry_rebuild_refresh_recovery_summary', 'reset_reentry_rebuild_recovery', False),
    ('closure_forecast_reset_reentry_rebuild_reentry_summary', 'reset_reentry_rebuild_recovery', False),
    ('closure_forecast_reset_reentry_rebuild_refresh_window_runs', 'reset_reentry_rebuild_recovery', False),
    ('recovering_from_confirmation_rebuild_reset_hotspots', 'reset_reentry_rebuild_recovery', False),
    ('recovering_from_clearance_rebuild_reset_hotspots', 'reset_reentry_rebuild_recovery', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_age_runs', 'reset_reentry_rebuild_reentry_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_persistence_score', 'reset_reentry_rebuild_reentry_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_persistence_status', 'reset_reentry_rebuild_reentry_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_persistence_reason', 'reset_reentry_rebuild_reentry_persistence', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_persistence_summary', 'reset_reentry_rebuild_reentry_persistence', False),
    ('closure_forecast_reset_reentry_rebuild_reentry_window_runs', 'reset_reentry_rebuild_reentry_persistence', False),
    ('just_reentered_rebuild_hotspots', 'reset_reentry_rebuild_reentry_persistence', False),
    ('holding_reset_reentry_rebuild_reentry_hotspots', 'reset_reentry_rebuild_reentry_persistence', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_churn_score', 'reset_reentry_rebuild_reentry_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_churn_status', 'reset_reentry_rebuild_reentry_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_churn_reason', 'reset_reentry_rebuild_reentry_persistence', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_churn_summary', 'reset_reentry_rebuild_reentry_persistence', False),
    ('reset_reentry_rebuild_reentry_churn_hotspots', 'reset_reentry_rebuild_reentry_persistence', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_freshness_status', 'reset_reentry_rebuild_reentry_freshness_decay', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_freshness_reason', 'reset_reentry_rebuild_reentry_freshness_decay', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_freshness_summary', 'reset_reentry_rebuild_reentry_freshness_decay', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_reset_status', 'reset_reentry_rebuild_reentry_freshness_decay', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_reset_reason', 'reset_reentry_rebuild_reentry_freshness_decay', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_reset_summary', 'reset_reentry_rebuild_reentry_freshness_decay', False),
    ('stale_reset_reentry_rebuild_reentry_hotspots', 'reset_reentry_rebuild_reentry_freshness_decay', False),
    ('fresh_reset_reentry_rebuild_reentry_signal_hotspots', 'reset_reentry_rebuild_reentry_freshness_decay', False),
    ('closure_forecast_reset_reentry_rebuild_reentry_decay_window_runs', 'reset_reentry_rebuild_reentry_freshness_decay', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_refresh_recovery_score', 'reset_reentry_rebuild_reentry_recovery', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_refresh_recovery_status', 'reset_reentry_rebuild_reentry_recovery', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_status', 'reset_reentry_rebuild_reentry_recovery', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_reason', 'reset_reentry_rebuild_reentry_recovery', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_refresh_recovery_summary', 'reset_reentry_rebuild_reentry_recovery', False),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_summary', 'reset_reentry_rebuild_reentry_recovery', False),
    ('closure_forecast_reset_reentry_rebuild_reentry_refresh_window_runs', 'reset_reentry_rebuild_reentry_recovery', False),
    ('recovering_from_confirmation_rebuild_reentry_reset_hotspots', 'reset_reentry_rebuild_reentry_recovery', False),
    ('recovering_from_clearance_rebuild_reentry_reset_hotspots', 'reset_reentry_rebuild_reentry_recovery', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_age_runs', 'reset_reentry_rebuild_reentry_restore_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_persistence_score', 'reset_reentry_rebuild_reentry_restore_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_persistence_status', 'reset_reentry_rebuild_reentry_restore_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_persistence_reason', 'reset_reentry_rebuild_reentry_restore_persistence', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_persistence_summary', 'reset_reentry_rebuild_reentry_restore_persistence', False),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_window_runs', 'reset_reentry_rebuild_reentry_restore_persistence', False),
    ('just_restored_rebuild_reentry_hotspots', 'reset_reentry_rebuild_reentry_restore_persistence', False),
    ('holding_reset_reentry_rebuild_reentry_restore_hotspots', 'reset_reentry_rebuild_reentry_restore_persistence', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_churn_score', 'reset_reentry_rebuild_reentry_restore_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_churn_status', 'reset_reentry_rebuild_reentry_restore_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_churn_reason', 'reset_reentry_rebuild_reentry_restore_persistence', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_churn_summary', 'reset_reentry_rebuild_reentry_restore_persistence', False),
    ('reset_reentry_rebuild_reentry_restore_churn_hotspots', 'reset_reentry_rebuild_reentry_restore_persistence', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_freshness_status', 'reset_reentry_rebuild_reentry_restore_freshness_decay', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_freshness_reason', 'reset_reentry_rebuild_reentry_restore_freshness_decay', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_freshness_summary', 'reset_reentry_rebuild_reentry_restore_freshness_decay', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_reset_status', 'reset_reentry_rebuild_reentry_restore_freshness_decay', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_reset_reason', 'reset_reentry_rebuild_reentry_restore_freshness_decay', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_reset_summary', 'reset_reentry_rebuild_reentry_restore_freshness_decay', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_refresh_recovery_score', 'reset_reentry_rebuild_reentry_restore_recovery', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_refresh_recovery_status', 'reset_reentry_rebuild_reentry_restore_recovery', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_status', 'reset_reentry_rebuild_reentry_restore_recovery', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_reason', 'reset_reentry_rebuild_reentry_restore_recovery', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_refresh_recovery_summary', 'reset_reentry_rebuild_reentry_restore_recovery', False),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_summary', 'reset_reentry_rebuild_reentry_restore_recovery', False),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_refresh_window_runs', 'reset_reentry_rebuild_reentry_restore_recovery', False),
    ('recovering_from_confirmation_rebuild_reentry_restore_reset_hotspots', 'reset_reentry_rebuild_reentry_restore_recovery', False),
    ('recovering_from_clearance_rebuild_reentry_restore_reset_hotspots', 'reset_reentry_rebuild_reentry_restore_recovery', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_age_runs', 'reset_reentry_rebuild_reentry_restore_rerestore_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_persistence_score', 'reset_reentry_rebuild_reentry_restore_rerestore_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_persistence_status', 'reset_reentry_rebuild_reentry_restore_rerestore_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_persistence_reason', 'reset_reentry_rebuild_reentry_restore_rerestore_persistence', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_persistence_summary', 'reset_reentry_rebuild_reentry_restore_rerestore_persistence', False),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_window_runs', 'reset_reentry_rebuild_reentry_restore_rerestore_persistence', False),
    ('just_rerestored_rebuild_reentry_hotspots', 'reset_reentry_rebuild_reentry_restore_rerestore_persistence', False),
    ('holding_reset_reentry_rebuild_reentry_restore_rerestore_hotspots', 'reset_reentry_rebuild_reentry_restore_rerestore_persistence', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_churn_score', 'reset_reentry_rebuild_reentry_restore_rerestore_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_churn_status', 'reset_reentry_rebuild_reentry_restore_rerestore_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_churn_reason', 'reset_reentry_rebuild_reentry_restore_rerestore_persistence', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_churn_summary', 'reset_reentry_rebuild_reentry_restore_rerestore_persistence', False),
    ('reset_reentry_rebuild_reentry_restore_rerestore_churn_hotspots', 'reset_reentry_rebuild_reentry_restore_rerestore_persistence', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_freshness_status', 'reset_reentry_rebuild_reentry_restore_rerestore_freshness_decay', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_freshness_reason', 'reset_reentry_rebuild_reentry_restore_rerestore_freshness_decay', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_freshness_summary', 'reset_reentry_rebuild_reentry_restore_rerestore_freshness_decay', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_reset_status', 'reset_reentry_rebuild_reentry_restore_rerestore_freshness_decay', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_reset_reason', 'reset_reentry_rebuild_reentry_restore_rerestore_freshness_decay', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_reset_summary', 'reset_reentry_rebuild_reentry_restore_rerestore_freshness_decay', False),
    ('stale_reset_reentry_rebuild_reentry_restore_rerestore_hotspots', 'reset_reentry_rebuild_reentry_restore_rerestore_freshness_decay', False),
    ('fresh_reset_reentry_rebuild_reentry_restore_rerestore_signal_hotspots', 'reset_reentry_rebuild_reentry_restore_rerestore_freshness_decay', False),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_decay_window_runs', 'reset_reentry_rebuild_reentry_restore_rerestore_freshness_decay', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_refresh_recovery_score', 'reset_reentry_rebuild_reentry_restore_rerestore_recovery', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_refresh_recovery_status', 'reset_reentry_rebuild_reentry_restore_rerestore_recovery', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_status', 'reset_reentry_rebuild_reentry_restore_rerestore_recovery', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_reason', 'reset_reentry_rebuild_reentry_restore_rerestore_recovery', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_refresh_recovery_summary', 'reset_reentry_rebuild_reentry_restore_rerestore_recovery', False),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_summary', 'reset_reentry_rebuild_reentry_restore_rerestore_recovery', False),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rerestore_refresh_window_runs', 'reset_reentry_rebuild_reentry_restore_rerestore_recovery', False),
    ('recovering_from_confirmation_rebuild_reentry_rerestore_reset_hotspots', 'reset_reentry_rebuild_reentry_restore_rerestore_recovery', False),
    ('recovering_from_clearance_rebuild_reentry_rerestore_reset_hotspots', 'reset_reentry_rebuild_reentry_restore_rerestore_recovery', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_age_runs', 'reset_reentry_rebuild_reentry_restore_rererestore_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_persistence_score', 'reset_reentry_rebuild_reentry_restore_rererestore_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_persistence_status', 'reset_reentry_rebuild_reentry_restore_rererestore_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_persistence_reason', 'reset_reentry_rebuild_reentry_restore_rererestore_persistence', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_persistence_summary', 'reset_reentry_rebuild_reentry_restore_rererestore_persistence', False),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_window_runs', 'reset_reentry_rebuild_reentry_restore_rererestore_persistence', False),
    ('just_rererestored_rebuild_reentry_hotspots', 'reset_reentry_rebuild_reentry_restore_rererestore_persistence', False),
    ('holding_reset_reentry_rebuild_reentry_restore_rererestore_hotspots', 'reset_reentry_rebuild_reentry_restore_rererestore_persistence', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_churn_score', 'reset_reentry_rebuild_reentry_restore_rererestore_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_churn_status', 'reset_reentry_rebuild_reentry_restore_rererestore_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_churn_reason', 'reset_reentry_rebuild_reentry_restore_rererestore_persistence', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_churn_summary', 'reset_reentry_rebuild_reentry_restore_rererestore_persistence', False),
    ('reset_reentry_rebuild_reentry_restore_rererestore_churn_hotspots', 'reset_reentry_rebuild_reentry_restore_rererestore_persistence', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_freshness_status', 'reset_reentry_rebuild_reentry_restore_rererestore_freshness_decay', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_freshness_reason', 'reset_reentry_rebuild_reentry_restore_rererestore_freshness_decay', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_freshness_summary', 'reset_reentry_rebuild_reentry_restore_rererestore_freshness_decay', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_reset_status', 'reset_reentry_rebuild_reentry_restore_rererestore_freshness_decay', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_reset_reason', 'reset_reentry_rebuild_reentry_restore_rererestore_freshness_decay', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_reset_summary', 'reset_reentry_rebuild_reentry_restore_rererestore_freshness_decay', False),
    ('stale_reset_reentry_rebuild_reentry_restore_rererestore_hotspots', 'reset_reentry_rebuild_reentry_restore_rererestore_freshness_decay', False),
    ('fresh_reset_reentry_rebuild_reentry_restore_rererestore_signal_hotspots', 'reset_reentry_rebuild_reentry_restore_rererestore_freshness_decay', False),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_decay_window_runs', 'reset_reentry_rebuild_reentry_restore_rererestore_freshness_decay', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_refresh_recovery_score', 'reset_reentry_rebuild_reentry_restore_rererestore_recovery', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_refresh_recovery_status', 'reset_reentry_rebuild_reentry_restore_rererestore_recovery', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerererestore_status', 'reset_reentry_rebuild_reentry_restore_rererestore_recovery', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerererestore_reason', 'reset_reentry_rebuild_reentry_restore_rererestore_recovery', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_refresh_recovery_summary', 'reset_reentry_rebuild_reentry_restore_rererestore_recovery', False),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rerererestore_summary', 'reset_reentry_rebuild_reentry_restore_rererestore_recovery', False),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rererestore_refresh_window_runs', 'reset_reentry_rebuild_reentry_restore_rererestore_recovery', False),
    ('recovering_from_confirmation_rebuild_reentry_rererestore_reset_hotspots', 'reset_reentry_rebuild_reentry_restore_rererestore_recovery', False),
    ('recovering_from_clearance_rebuild_reentry_rererestore_reset_hotspots', 'reset_reentry_rebuild_reentry_restore_rererestore_recovery', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerererestore_age_runs', 'reset_reentry_rebuild_reentry_restore_rerererestore_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerererestore_persistence_score', 'reset_reentry_rebuild_reentry_restore_rerererestore_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerererestore_persistence_status', 'reset_reentry_rebuild_reentry_restore_rerererestore_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerererestore_persistence_reason', 'reset_reentry_rebuild_reentry_restore_rerererestore_persistence', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rerererestore_persistence_summary', 'reset_reentry_rebuild_reentry_restore_rerererestore_persistence', False),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rerererestore_window_runs', 'reset_reentry_rebuild_reentry_restore_rerererestore_persistence', False),
    ('just_rerererestored_rebuild_reentry_hotspots', 'reset_reentry_rebuild_reentry_restore_rerererestore_persistence', False),
    ('holding_reset_reentry_rebuild_reentry_restore_rerererestore_hotspots', 'reset_reentry_rebuild_reentry_restore_rerererestore_persistence', False),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerererestore_churn_score', 'reset_reentry_rebuild_reentry_restore_rerererestore_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerererestore_churn_status', 'reset_reentry_rebuild_reentry_restore_rerererestore_persistence', True),
    ('primary_target_closure_forecast_reset_reentry_rebuild_reentry_restore_rerererestore_churn_reason', 'reset_reentry_rebuild_reentry_restore_rerererestore_persistence', True),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_rerererestore_churn_summary', 'reset_reentry_rebuild_reentry_restore_rerererestore_persistence', False),
    ('reset_reentry_rebuild_reentry_restore_rerererestore_churn_hotspots', 'reset_reentry_rebuild_reentry_restore_rerererestore_persistence', False),
    ('stale_reset_reentry_rebuild_reentry_restore_hotspots', 'reset_reentry_rebuild_reentry_restore_freshness_decay', False),
    ('fresh_reset_reentry_rebuild_reentry_restore_signal_hotspots', 'reset_reentry_rebuild_reentry_restore_freshness_decay', False),
    ('closure_forecast_reset_reentry_rebuild_reentry_restore_decay_window_runs', 'reset_reentry_rebuild_reentry_restore_freshness_decay', False),
    ('sustained_class_hotspots', 'class_trust_momentum', False),
    ('oscillating_class_hotspots', 'class_trust_momentum', False),
    ('decision_memory_status', 'decision_memory', False),
    ('primary_target_last_seen_at', 'decision_memory', False),
    ('primary_target_last_intervention', 'decision_memory', False),
    ('primary_target_last_outcome', 'decision_memory', False),
    ('primary_target_resolution_evidence', 'decision_memory', False),
    ('recent_interventions', 'decision_memory', False),
    ('recently_quieted_count', 'decision_memory', False),
    ('confirmed_resolved_count', 'decision_memory', False),
    ('reopened_after_resolution_count', 'decision_memory', False),
    ('decision_memory_window_runs', 'decision_memory', False),
    ('resolution_evidence_summary', 'decision_memory', False),
)


def build_resolution_trend_payload(
    *,
    apply_chain: dict[str, Any],
    summary_context: dict[str, Any],
    decision_memory_map: dict[str, dict],
    class_transition_health_summary: Callable[..., Any],
    class_transition_resolution_summary: Callable[..., Any],
    closure_forecast_hysteresis_summary: Callable[..., Any],
) -> dict[str, Any]:
    class_transition_resolution = apply_chain['class_transition_resolution']
    closure_forecast_momentum = apply_chain['closure_forecast_momentum']
    primary_target = summary_context['primary_target']
    _class_transition_health_summary = class_transition_health_summary
    _class_transition_resolution_summary = class_transition_resolution_summary
    _closure_forecast_hysteresis_summary = closure_forecast_hysteresis_summary
    payload: dict[str, Any] = {}
    sources = {**apply_chain, "decision_memory": summary_context["decision_memory"]}
    payload.update({
        "class_transition_health_summary": _class_transition_health_summary(
            primary_target,
            class_transition_resolution["stalled_transition_hotspots"],
        )
        if primary_target
        else class_transition_resolution["class_transition_health_summary"],
        "class_transition_resolution_summary": _class_transition_resolution_summary(
            primary_target,
            class_transition_resolution["resolving_transition_hotspots"],
            class_transition_resolution["stalled_transition_hotspots"],
        )
        if primary_target
        else class_transition_resolution["class_transition_resolution_summary"],
        "closure_forecast_hysteresis_summary": _closure_forecast_hysteresis_summary(
            primary_target,
            closure_forecast_momentum["sustained_confirmation_hotspots"],
            closure_forecast_momentum["sustained_clearance_hotspots"],
        )
        if primary_target
        else closure_forecast_momentum["closure_forecast_hysteresis_summary"],
        "decision_memory_map": decision_memory_map,
    })
    _emit_resolution_payload_entries(
        payload,
        primary_target=primary_target,
        sources=sources,
        entries=_RESOLUTION_PAYLOAD_ENTRIES,
    )
    return payload
