"""Writers for workbook hidden data sheets."""

from __future__ import annotations

from openpyxl import Workbook

from src.excel_detail_helpers import write_hidden_table_sheet


def write_hidden_data_tables(
    wb: Workbook,
    rows: dict[str, list[list[object]]],
    *,
    trend_history_window: int,
) -> None:
    specs = [
        (
            "repo_rows",
            "Data_Repos",
            "tblRepos",
            [
                "Repo",
                "Full Name",
                "Language",
                "Private",
                "Archived",
                "Overall Score",
                "Interest Score",
                "Grade",
                "Tier",
                "Security Label",
                "Collections",
                "Ship Readiness",
                "Maintenance Risk",
                "Showcase Value",
                "Security Posture",
                "Momentum",
                "Portfolio Fit",
            ],
        ),
        ("dimension_rows", "Data_Dimensions", "tblDimensions", ["Repo", "Dimension", "Score", "Max Score", "Findings"]),
        ("lens_rows", "Data_Lenses", "tblLenses", ["Repo", "Lens", "Score", "Orientation", "Summary", "Drivers"]),
        ("history_rows", "Data_History", "tblHistory", ["Series", "Run Index", "Score"]),
        (
            "trend_matrix_rows",
            "Data_TrendMatrix",
            "tblTrendMatrix",
            ["Repo"] + [f"Run {index}" for index in range(1, trend_history_window + 1)],
        ),
        (
            "portfolio_history_rows",
            "Data_PortfolioHistory",
            "tblPortfolioHistory",
            [
                "Run Index",
                "Date",
                "Average Score",
                "Repos Audited",
                "Shipped",
                "Functional",
                "Security Avg",
                "Review Emitted",
                "Campaign Drift",
                "Governance Drift",
            ],
        ),
        (
            "rollup_rows",
            "Data_Rollups",
            "tblRollups",
            [
                "Profile",
                "Collection",
                "Lens",
                "Repo Count",
                "Average Lens Score",
                "Top Repo",
                "Top Profile Score",
            ],
        ),
        (
            "review_target_rows",
            "Data_ReviewTargets",
            "tblReviewTargets",
            ["Repo", "Title", "Severity", "Next Step", "Decision Hint", "Safe To Defer"],
        ),
        (
            "review_history_rows",
            "Data_ReviewHistory",
            "tblReviewHistoryData",
            [
                "Review ID",
                "Source Run",
                "Generated",
                "Materiality",
                "Changes",
                "Status",
                "Decision State",
                "Sync State",
                "Safe To Defer",
                "Emitted",
            ],
        ),
        (
            "security_rows",
            "Data_Security",
            "tblSecurityData",
            [
                "Repo",
                "Label",
                "Score",
                "Secrets",
                "Dangerous Files",
                "SECURITY.md",
                "Dependabot",
                "Evidence",
            ],
        ),
        (
            "security_control_rows",
            "Data_SecurityControls",
            "tblSecurityControls",
            ["Repo", "Control", "Status", "Source", "Details"],
        ),
        (
            "security_provider_rows",
            "Data_SecurityProviders",
            "tblSecurityProviders",
            ["Repo", "Provider", "Available", "Score", "Reason"],
        ),
        (
            "security_alert_rows",
            "Data_SecurityAlerts",
            "tblSecurityAlerts",
            ["Repo", "Alert Type", "Open Count", "Status"],
        ),
        (
            "action_rows",
            "Data_Actions",
            "tblActions",
            [
                "Repo",
                "Key",
                "Title",
                "Lens",
                "Effort",
                "Confidence",
                "Expected Lens Delta",
                "Expected Tier Movement",
                "Rationale",
            ],
        ),
        (
            "collection_rows",
            "Data_Collections",
            "tblCollections",
            ["Collection", "Repo", "Rank", "Reason", "Description"],
        ),
        (
            "portfolio_catalog_rows",
            "Data_PortfolioCatalog",
            "tblPortfolioCatalogData",
            [
                "Repo",
                "Full Name",
                "Owner",
                "Team",
                "Purpose",
                "Lifecycle",
                "Criticality",
                "Review Cadence",
                "Disposition",
                "Maturity Program",
                "Target Maturity",
                "Operating Path",
                "Path Override",
                "Path Confidence",
                "Notes",
                "Intent Alignment",
                "Intent Alignment Reason",
                "Catalog Line",
            ],
        ),
        (
            "scorecard_rows",
            "Data_Scorecards",
            "tblScorecardsData",
            [
                "Repo",
                "Full Name",
                "Program",
                "Program Label",
                "Score",
                "Maturity Level",
                "Target Maturity",
                "Status",
                "Passed Rules",
                "Applicable Rules",
                "Failed Rule Keys",
                "Top Gaps",
                "Summary",
            ],
        ),
        (
            "implementation_hotspot_rows",
            "Data_ImplementationHotspots",
            "tblImplementationHotspotsData",
            [
                "Repo",
                "Full Name",
                "Scope",
                "Path",
                "Module",
                "Category",
                "Pressure Score",
                "Suggestion Type",
                "Why It Matters",
                "Suggested First Move",
                "Signal Summary",
            ],
        ),
        (
            "operator_outcome_rows",
            "Data_OperatorOutcomes",
            "tblOperatorOutcomesData",
            ["Metric", "Status", "Value", "Numerator", "Denominator", "Summary"],
        ),
        (
            "action_sync_outcome_rows",
            "Data_ActionSyncOutcomes",
            "tblActionSyncOutcomesData",
            [
                "Campaign Type",
                "Label",
                "Latest Target",
                "Latest Run Mode",
                "Recent Apply Count",
                "Monitored Repo Count",
                "Monitoring State",
                "Pressure Effect",
                "Drift State",
                "Reopen State",
                "Rollback State",
                "Follow-Up Recommendation",
                "Top Repos",
                "Summary",
            ],
        ),
        (
            "campaign_tuning_rows",
            "Data_CampaignTuning",
            "tblCampaignTuningData",
            [
                "Campaign Type",
                "Label",
                "Tuning Status",
                "Recommendation Bias",
                "Judged Count",
                "Monitor Now Count",
                "Holding Clean Rate",
                "Drift Return Rate",
                "Reopen Rate",
                "Rollback Watch Rate",
                "Pressure Reduction Rate",
                "Summary",
            ],
        ),
        (
            "intervention_ledger_rows",
            "Data_InterventionLedger",
            "tblInterventionLedgerData",
            [
                "Repo",
                "Latest Tier",
                "Latest Score",
                "Recent Intervention Count",
                "Last Intervention",
                "Pressure Trend",
                "Hotspot Persistence",
                "Scorecard Trend",
                "Campaign Follow Through",
                "Historical Intelligence Status",
                "Summary",
            ],
        ),
        (
            "action_sync_automation_rows",
            "Data_ActionSyncAutomation",
            "tblActionSyncAutomationData",
            [
                "Campaign Type",
                "Label",
                "Automation Posture",
                "Review Required",
                "Requires Approval",
                "Recommended Command",
                "Recommended Follow Up",
                "Summary",
            ],
        ),
        (
            "approval_ledger_rows",
            "Data_ApprovalLedger",
            "tblApprovalLedgerData",
            [
                "Approval ID",
                "Subject Type",
                "Subject Key",
                "Label",
                "Approval State",
                "Follow-Up State",
                "Source Run ID",
                "Fingerprint",
                "Approved At",
                "Approved By",
                "Last Reviewed At",
                "Last Reviewed By",
                "Follow-Up Cadence Days",
                "Next Follow-Up Due At",
                "Stale Approval",
                "Approval Ready",
                "Apply Ready After Approval",
                "Approval Command",
                "Follow-Up Command",
                "Manual Apply Command",
                "Summary",
            ],
        ),
        (
            "scenario_rows",
            "Data_Scenarios",
            "tblScenarios",
            [
                "Key",
                "Title",
                "Lens",
                "Repo Count",
                "Average Expected Lens Delta",
                "Projected Tier Promotions",
            ],
        ),
        (
            "governance_rows",
            "Data_Governance",
            "tblGovernancePreview",
            ["Repo", "Key", "Priority", "Title", "Expected Lift", "Effort", "Source", "Why"],
        ),
        (
            "campaign_rows",
            "Data_Campaigns",
            "tblCampaigns",
            ["Campaign Type", "Label", "Profile", "Collection", "Actions", "Repos"],
        ),
        (
            "writeback_rows",
            "Data_Writeback",
            "tblWriteback",
            ["Repo", "Target", "Status", "URL", "Before", "After"],
        ),
        (
            "operator_queue_rows",
            "Data_OperatorQueue",
            "tblOperatorQueueData",
            [
                "Item ID",
                "Repo",
                "Kind",
                "Lane",
                "Priority",
                "Title",
                "Summary",
                "Recommended Action",
                "Source Run",
                "Age Days",
                "Links",
                "Follow-Through Age Runs",
                "Follow-Through Status",
                "Follow-Through Checkpoint Status",
                "Follow-Through Summary",
                "Follow-Through Last Touch",
                "Follow-Through Next Checkpoint",
                "Follow-Through Evidence Hint",
                "Follow-Through Escalation Status",
                "Follow-Through Escalation Summary",
                "Follow-Through Escalation Reason",
                "Follow-Through Recovery Age Runs",
                "Follow-Through Recovery Status",
                "Follow-Through Recovery Summary",
                "Follow-Through Recovery Reason",
                "Follow-Through Recovery Persistence Age Runs",
                "Follow-Through Recovery Persistence Status",
                "Follow-Through Recovery Persistence Summary",
                "Follow-Through Recovery Persistence Reason",
                "Follow-Through Relapse Churn Status",
                "Follow-Through Relapse Churn Summary",
                "Follow-Through Relapse Churn Reason",
                "Follow-Through Recovery Freshness Age Runs",
                "Follow-Through Recovery Freshness Status",
                "Follow-Through Recovery Freshness Summary",
                "Follow-Through Recovery Freshness Reason",
                "Follow-Through Recovery Decay Status",
                "Follow-Through Recovery Decay Summary",
                "Follow-Through Recovery Decay Reason",
                "Follow-Through Recovery Memory Reset Status",
                "Follow-Through Recovery Memory Reset Summary",
                "Follow-Through Recovery Memory Reset Reason",
                "Follow-Through Recovery Rebuild Strength Age Runs",
                "Follow-Through Recovery Rebuild Strength Status",
                "Follow-Through Recovery Rebuild Strength Summary",
                "Follow-Through Recovery Rebuild Strength Reason",
                "Follow-Through Recovery Reacquisition Status",
                "Follow-Through Recovery Reacquisition Summary",
                "Follow-Through Recovery Reacquisition Reason",
                "Follow-Through Recovery Reacquisition Durability Age Runs",
                "Follow-Through Recovery Reacquisition Durability Status",
                "Follow-Through Recovery Reacquisition Durability Summary",
                "Follow-Through Recovery Reacquisition Durability Reason",
                "Follow-Through Recovery Reacquisition Consolidation Status",
                "Follow-Through Recovery Reacquisition Consolidation Summary",
                "Follow-Through Recovery Reacquisition Consolidation Reason",
                "Follow-Through Reacquisition Softening Decay Age Runs",
                "Follow-Through Reacquisition Softening Decay Status",
                "Follow-Through Reacquisition Softening Decay Summary",
                "Follow-Through Reacquisition Softening Decay Reason",
                "Follow-Through Reacquisition Confidence Retirement Status",
                "Follow-Through Reacquisition Confidence Retirement Summary",
                "Follow-Through Reacquisition Confidence Retirement Reason",
                "Follow-Through Reacquisition Revalidation Recovery Age Runs",
                "Follow-Through Reacquisition Revalidation Recovery Status",
                "Follow-Through Reacquisition Revalidation Recovery Summary",
                "Follow-Through Reacquisition Revalidation Recovery Reason",
                "Catalog Line",
                "Operating Path",
                "Intent Alignment",
                "Intent Alignment Reason",
                "Scorecard Line",
                "Maturity Gap Summary",
                "Action Sync Stage",
                "Action Sync Reason",
                "Suggested Campaign",
                "Suggested Writeback Target",
                "Action Sync Line",
                "Apply Packet State",
                "Apply Packet Summary",
                "Apply Packet Command",
                "Post-Apply State",
                "Post-Apply Summary",
                "Post-Apply Line",
                "Campaign Tuning Status",
                "Campaign Tuning Summary",
                "Campaign Tuning Line",
                "Historical Intelligence Status",
                "Historical Intelligence Summary",
                "Historical Intelligence Line",
                "Approval State",
                "Approval Summary",
                "Approval Line",
            ],
        ),
        (
            "operator_repo_rollups",
            "Data_OperatorRepoRollups",
            "tblOperatorRepoRollups",
            [
                "Repo",
                "Total Items",
                "Blocked",
                "Urgent",
                "Ready",
                "Deferred",
                "Primary Kind",
                "Top Priority",
                "Top Title",
                "Recommended Action",
            ],
        ),
        (
            "material_rollups",
            "Data_MaterialChangeRollups",
            "tblMaterialChangeRollups",
            ["Repo", "Change Type", "Count", "Max Severity", "Sample Title"],
        ),
        (
            "repo_detail_rows",
            "Data_RepoDetail",
            "tblRepoDetailData",
            [
                "Repo",
                "URL",
                "Language",
                "Description",
                "Overall Score",
                "Interest Score",
                "Grade",
                "Tier",
                "Badges",
                "Flags",
                "Collections",
                "Security Label",
                "Security Score",
                "Ship Lens Summary",
                "Momentum Lens Summary",
                "Security Lens Summary",
                "Portfolio Fit Summary",
                "Trend Sparkline",
                "Top Positive Drivers",
                "Top Negative Drivers",
                "Next Tier Gap Summary",
                "Next Best Action",
                "Next Best Action Rationale",
                "Top Hotspot 1",
                "Top Hotspot 2",
                "Top Hotspot 3",
                "Top Action 1",
                "Top Action 2",
                "Top Action 3",
                "Last Movement",
                "Recent Change Summary",
                "Follow-Through Status",
                "Follow-Through Summary",
                "Checkpoint Timing",
                "Escalation",
                "Escalation Summary",
                "Recovery / Retirement",
                "Recovery / Retirement Summary",
                "Recovery Persistence",
                "Recovery Persistence Summary",
                "Relapse Churn",
                "Relapse Churn Summary",
                "Recovery Freshness",
                "Recovery Freshness Summary",
                "Recovery Memory Reset",
                "Recovery Memory Reset Summary",
                "Recovery Rebuild Strength",
                "Recovery Rebuild Strength Summary",
                "Recovery Reacquisition",
                "Recovery Reacquisition Summary",
                "Reacquisition Durability",
                "Reacquisition Durability Summary",
                "Reacquisition Confidence",
                "Reacquisition Confidence Summary",
                "Reacquisition Softening Decay",
                "Reacquisition Softening Decay Summary",
                "Reacquisition Confidence Retirement",
                "Reacquisition Confidence Retirement Summary",
                "Revalidation Recovery",
                "Revalidation Recovery Summary",
                "What Would Count As Progress",
                "Catalog",
                "Operating Path",
                "Intent Alignment",
                "Scorecard",
                "Maturity Gap",
                "Where To Start Summary",
                "Implementation Hotspot 1",
                "Implementation Hotspot 2",
                "Implementation Hotspot 3",
            ],
        ),
        (
            "repo_dimension_rollup_rows",
            "Data_RepoDimensionRollups",
            "tblRepoDimensionRollups",
            ["Lookup Key", "Repo", "Rank", "Dimension", "Score", "Summary"],
        ),
        (
            "repo_history_rollup_rows",
            "Data_RepoHistoryRollups",
            "tblRepoHistoryRollups",
            ["Repo", "Run Index", "Score", "Sparkline"],
        ),
        (
            "run_change_rollup_rows",
            "Data_RunChangeRollups",
            "tblRunChangeRollups",
            ["Metric", "Value", "Summary"],
        ),
        (
            "run_change_repo_rows",
            "Data_RunChangeRepoData",
            "tblRunChangeRepoData",
            ["Section", "Repo", "Delta", "Old Tier", "New Tier", "Security", "Hotspots", "Collections", "Summary"],
        ),
        ("lookup_rows", "Lookups", "tblLookups", ["Type", "Key", "Value"]),
    ]

    for row_key, sheet_name, table_name, headers in specs:
        write_hidden_table_sheet(wb, sheet_name, table_name, headers, rows[row_key])
