"""Create GitHub Issues from audit quick wins."""
from __future__ import annotations

import sys

from src.github_client import GitHubClient


def create_audit_issues(
    quick_wins: list[dict],
    username: str,
    client: GitHubClient,
    *,
    dry_run: bool = False,
    label: str = "audit",
) -> dict[str, list[dict]]:
    """Create GitHub Issues from quick win actions. Returns created/skipped summary."""
    created: list[dict] = []
    skipped: list[dict] = []

    for qw in quick_wins:
        repo_name = qw.get("name", "")
        if not repo_name:
            continue

        # Dedup: check for existing [Audit] issues
        try:
            existing = client.list_repo_issues(username, repo_name, state="open")
            if any(i.get("title", "").startswith("[Audit]") for i in existing):
                skipped.append({"repo": repo_name, "reason": "existing [Audit] issue found"})
                continue
        except Exception:
            pass  # If we can't check, proceed with creation

        actions = qw.get("actions", [])
        title = f"[Audit] {repo_name}: {actions[0] if actions else 'Improve audit score'}"

        body_parts = [
            f"## Audit Findings for {repo_name}",
            f"",
            f"**Current Score:** {qw.get('score', 0):.2f}",
            f"**Current Tier:** {qw.get('current_tier', 'unknown')}",
            f"**Next Tier:** {qw.get('next_tier', 'unknown')} (gap: {qw.get('gap', 0):.2f})",
            f"",
            f"### Recommended Actions",
        ]
        for i, action in enumerate(actions, 1):
            body_parts.append(f"{i}. {action}")
        body_parts.extend(["", "_Generated by GitHub Repo Auditor_"])
        body = "\n".join(body_parts)

        if dry_run:
            print(f"  [dry-run] Would create issue: {title}", file=sys.stderr)
            created.append({"repo": repo_name, "title": title, "dry_run": True})
        else:
            try:
                result = client.create_issue(username, repo_name, {
                    "title": title,
                    "body": body,
                    "labels": [label],
                })
                if result:
                    created.append({
                        "repo": repo_name,
                        "title": title,
                        "url": result.get("html_url", ""),
                    })
                    print(f"  Created issue: {title}", file=sys.stderr)
            except Exception as e:
                print(f"  Failed to create issue for {repo_name}: {e}", file=sys.stderr)

    return {"created": created, "skipped": skipped}
