"""AI portfolio narrative — generates human-readable analysis using Claude API."""
from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path


def _build_prompt(report_data: dict) -> str:
    """Build a focused prompt from audit data."""
    tiers = report_data.get("tier_distribution", {})
    lang_dist = report_data.get("language_distribution", {})
    summary = report_data.get("summary", {})
    top_langs = list(lang_dist.items())[:8]

    return f"""Analyze this developer's GitHub portfolio and write a concise 3-paragraph narrative.

Portfolio stats:
- {report_data.get('repos_audited', 0)} repositories audited
- Average completeness score: {report_data.get('average_score', 0):.2f} / 1.00
- Portfolio grade: {report_data.get('portfolio_grade', '?')}
- Tier distribution: {json.dumps(tiers)}
- Top languages: {', '.join(f'{l} ({c} repos)' for l, c in top_langs)}
- Highest scored: {', '.join(summary.get('highest_scored', [])[:5])}
- Lowest scored: {', '.join(summary.get('lowest_scored', [])[:5])}
- Most active: {', '.join(summary.get('most_active', [])[:5])}

Write exactly 3 paragraphs:
1. Overall portfolio assessment — strengths and character
2. Patterns you notice — tech preferences, completion habits, areas of focus
3. Specific recommendations — what to prioritize next

Be direct, specific, and actionable. Reference repo names where relevant."""


def generate_narrative(report_data: dict, output_dir: Path) -> dict:
    """Generate AI narrative. Returns {narrative_path} or {skipped, reason}."""
    api_key = os.environ.get("ANTHROPIC_API_KEY", "").strip()
    if not api_key:
        print("  ANTHROPIC_API_KEY not set. Skipping narrative.", file=sys.stderr)
        return {"skipped": True, "reason": "no api key"}

    try:
        import anthropic
    except ImportError:
        print("  anthropic package not installed. Skipping narrative.", file=sys.stderr)
        return {"skipped": True, "reason": "anthropic not installed"}

    prompt = _build_prompt(report_data)
    username = report_data.get("username", "unknown")
    date = report_data.get("generated_at", "")[:10] or datetime.now(timezone.utc).strftime("%Y-%m-%d")

    try:
        client = anthropic.Anthropic(api_key=api_key)
        message = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=1024,
            messages=[{"role": "user", "content": prompt}],
        )
        narrative_text = message.content[0].text
    except Exception as exc:
        print(f"  Narrative generation failed: {exc}", file=sys.stderr)
        return {"skipped": True, "reason": str(exc)}

    lines = [
        f"# Portfolio Narrative: {username}",
        "",
        f"*AI-generated analysis from {date} audit data.*",
        "",
        narrative_text,
        "",
        "---",
        f"*Generated by [GithubRepoAuditor](https://github.com/saagpatel/GithubRepoAuditor) + Claude*",
        "",
    ]

    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"narrative-{date}.md"
    path.write_text("\n".join(lines))
    print(f"  Narrative generated: {path}", file=sys.stderr)
    return {"narrative_path": path}
