"""Portfolio README generator — produces a GitHub profile-ready PORTFOLIO.md."""
from __future__ import annotations

from pathlib import Path

from src.badge_export import GRADE_COLORS, _static_badge_url


def _tier_repos(audits: list[dict], tier: str) -> list[dict]:
    """Filter and sort audits by tier, descending by score."""
    return sorted(
        [a for a in audits if a.get("completeness_tier") == tier],
        key=lambda a: a.get("overall_score", 0),
        reverse=True,
    )


def _repo_table(repos: list[dict]) -> list[str]:
    """Build a markdown table of repos."""
    if not repos:
        return ["*None*", ""]
    lines = [
        "| Project | Grade | Description | Language |",
        "|---------|-------|-------------|----------|",
    ]
    for a in repos:
        m = a.get("metadata", {})
        name = m.get("name", "")
        url = m.get("html_url", "")
        grade = a.get("grade", "F")
        desc = (m.get("description") or "").replace("|", "—")[:80]
        lang = m.get("language") or "—"
        link = f"[{name}]({url})" if url else name
        lines.append(f"| {link} | {grade} | {desc} | {lang} |")
    lines.append("")
    return lines


def export_portfolio_readme(report_data: dict, output_dir: Path) -> dict:
    """Generate PORTFOLIO.md. Returns {readme_path}."""
    username = report_data.get("username", "unknown")
    date = report_data.get("generated_at", "")[:10]
    repos_audited = report_data.get("repos_audited", 0)
    grade = report_data.get("portfolio_grade", "F")
    avg_score = report_data.get("average_score", 0)
    tiers = report_data.get("tier_distribution", {})
    shipped_count = tiers.get("shipped", 0)
    audits = report_data.get("audits", [])

    from src.scorer import letter_grade
    avg_grade = letter_grade(avg_score)

    lines = [
        f"# Portfolio: {username}",
        "",
        f"![grade]({_static_badge_url('portfolio', grade, GRADE_COLORS.get(grade, 'red'))})",
        f"![repos]({_static_badge_url('repos audited', str(repos_audited), 'blue')})",
        f"![shipped]({_static_badge_url('shipped', str(shipped_count), 'brightgreen')})",
        f"![avg score]({_static_badge_url('avg score', f'{avg_score:.2f}', GRADE_COLORS.get(avg_grade, 'yellow'))})",
        "",
        f"*{repos_audited} repositories analyzed on {date}.*",
        "",
    ]

    # Flagship Projects
    shipped = _tier_repos(audits, "shipped")
    lines.append(f"## Flagship Projects ({len(shipped)})")
    lines.append("")
    lines.extend(_repo_table(shipped))

    # In Progress
    functional = _tier_repos(audits, "functional")
    wip = _tier_repos(audits, "wip")
    lines.append(f"## In Progress ({len(functional) + len(wip)})")
    lines.append("")

    if functional:
        lines.append(f"### Functional ({len(functional)})")
        lines.append("")
        lines.extend(_repo_table(functional))

    if wip:
        lines.append(f"### Work in Progress ({len(wip)})")
        lines.append("")
        lines.extend(_repo_table(wip))

    # Tech Stack
    lang_dist = report_data.get("language_distribution", {})
    if lang_dist:
        lines.append("## Tech Stack")
        lines.append("")
        lines.append("| Language | Repos |")
        lines.append("|----------|-------|")
        for lang, count in sorted(lang_dist.items(), key=lambda x: x[1], reverse=True)[:15]:
            lines.append(f"| {lang} | {count} |")
        lines.append("")

    # Distribution
    if tiers:
        total = sum(tiers.values())
        lines.append("## Distribution")
        lines.append("")
        lines.append("| Tier | Count | % |")
        lines.append("|------|-------|---|")
        for tier_name in ["shipped", "functional", "wip", "skeleton", "abandoned"]:
            count = tiers.get(tier_name, 0)
            pct = round(count / total * 100) if total else 0
            lines.append(f"| {tier_name.capitalize()} | {count} | {pct}% |")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [GithubRepoAuditor](https://github.com/saagpatel/GithubRepoAuditor)*")
    lines.append("")

    output_dir.mkdir(parents=True, exist_ok=True)
    readme_path = output_dir / "PORTFOLIO.md"
    readme_path.write_text("\n".join(lines))

    return {"readme_path": readme_path}
